name: Tests

on:
  pull_request:
  push:
    branches:
      - main

env:
  CC_TEST_REPORTER_ID: d25b4abd6845e37e3721694d8c9c7f025e3000e67741828467de028d1ce304c6

jobs:
  testing:
    name: Tests
    runs-on: ubuntu-20.04
    timeout-minutes: 15

    strategy:
      matrix:
        node: [ '14.17', '16.13', '18.13' ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use correct Node.js version
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: yarn install

      - name: Build package (just in case build fails)
        run: yarn build

      - name: Run tests with coverage
        uses: paambaati/codeclimate-action@v2.7.5
        with:
          coverageCommand: yarn test:cov
